project:
  type: website

website:
  title: "Quiz 2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-population.qmd
        text: Life Expectancy and Population
      - href: life-gdp.qmd
        text: Life Expectancy and GDP per Capita
      - href: country.qmd
        text: Country Analysis
      - about.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

render:
  output-dir: docs 

